# Generated by Django 4.2.27 on 2025-12-16 00:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EpubFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='epubs/%Y/%m/%d')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('p', 'pending'), ('l', 'loading'), ('c', 'completed'), ('f', 'failed')], default='p', max_length=1)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
