# Generated by Django 4.2.27 on 2025-12-19 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_trees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epubfile',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('pr', 'processing'), ('c', 'completed'), ('f', 'failed')], default='p', max_length=2),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('aliases', models.JSONField(default=list)),
                ('mention_count', models.IntegerField(default=0)),
                ('first_appearance_chapter', models.IntegerField(null=True)),
                ('epub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='book_trees.epubfile')),
            ],
            options={
                'ordering': ['-mention_count'],
                'unique_together': {('epub', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('supporting_text', models.TextField(blank=True)),
                ('chapter_found', models.IntegerField(blank=True, null=True)),
                ('character_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_character_1', to='book_trees.character')),
                ('character_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationshios_as_character_2', to='book_trees.character')),
                ('epub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_trees.epubfile')),
            ],
            options={
                'unique_together': {('character_1', 'character_2', 'relationship_type')},
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('chapter_number', models.IntegerField()),
                ('epub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='book_trees.epubfile')),
            ],
            options={
                'ordering': ['epub', 'chapter_number'],
                'unique_together': {('epub', 'chapter_number')},
            },
        ),
    ]
